# Generated by Django 2.2.10 on 2020-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200322_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='ratio',
            field=models.CharField(choices=[('pionowe', 'pionowe'), ('poziome', 'poziome'), ('kwadrat', 'kwadratowe')], default='pionowe', max_length=15),
        ),
    ]
