# Generated by Django 3.0.3 on 2020-03-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0002_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
